### ISSUE TITLE
Pointers' deallocation responsability

### ISSUE THREAD

**Issue by gbonnefille** [ccsdsmo/malc#44]
Running `valgrind` on test that encounter [failures](https://travis-ci.org/gbonnefille/malc/builds/386878736) revealed some double-free.

One example concerns the `sourceuri` attribute of `mal_updateheader`. In `test/malzmq_pubsub_app/src/pubsub_app_mypublisher.c` this attribute is provided from `mal_endpoint`. Thus, the effective char arry is *owned* both by `mal_updateheader` and `mal_endpoint` and when they both deallocate the pointer, unpredictable behaviour occurs.

MAL/C has to decide a logic for such situation.
Does the `*_set_*` method transfer the responsibility to the callee *object* or does it remains to the *caller*, in which case the *callee* has to duplicate the received object ?

**Comment by gbonnefille** [comment]
Just because:

- memory should be carefully deallocated
- it should be possible to provide const object that cannot be deallocated

then I feel the most sustainable approach is to systematically clone all received objects.

**Comment by freyssin** [comment]
The MAL/C logic means that the responsibility for the deallocation belongs to the containing object. In order to avoid useless copies, the _get_ methods do not duplicate the elements they return. So if these elements are used by a _set_ method, it is the user's responsibility to explicitly duplicate these elements.

In order to facilitate the detection of possible issues by the compiler the use of const objects on the _get_ methods will be generalized.

**Comment by freyssin** [comment]
The use of const qualifier is not easy. For example, in the description of this issue the returned URI is often used to initialize the uri_from field of a MAL message. To avoid too many recopies the message object allows to specify if this URI is his responsibility. The use of the qualifier const would destroy this optimization.
As a result, the signature of the _get_ methods will evolve but not systematically.
